development:
  adapter: postgresql
  encoding: utf8
  database: wizmenu-dev
  pool: 5
  timeout: 10000

test:
  adapter: postgresql
  encoding: utf8
  database: wizmenu-test
  pool: 5
  timeout: 10000

production:
  adapter: postgresql
  encoding: utf8
  database: wizmenu
  pool: 5
  timeout: 10000
